version: "3"

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8080:80"
      - "433:433"
    depends_on:
      - php-fpm
  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=projectdb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./database/data:/var/lib/mysql
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    restart: always
    container_name: phpmyadmin
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: docker